### ISSUE TITLE
Crash upon restarting game after inital load correctly the first time

### ISSUE THREAD

**Issue by scalda** [RicardoTheCoder/MiniMoos#1]
having a crash with this after adding it and restarting the game the 2nd time, after adding the mod I had no issues loading up and getting in the game but once I restarted it I am getting the below crash

[report](https://pastebin.com/Su8ayYF2)

regards

scalda

**Comment by IRicTheCoder** [comment]
@scalda That is a problem with the integration between Mini Moos and Mine Addons. A new version of Mine Addons is being released and it should fix the problem ;)

**Comment by scalda** [comment]
ok thanks any idea how long as i want to get the foolcraft update out today if possible

**Comment by IRicTheCoder** [comment]
@scalda Just got released now, it is already available on the curse launcher ;)

**Comment by scalda** [comment]
thanks, this version worked
