### ISSUE TITLE
Crash with foolcraft 2.3.1 and mini moos 1.2

### ISSUE THREAD

**Issue by scalda** [RicardoTheCoder/MiniMoos#11]
- [x] I am using a release version of the mod
- [ x] I have mods that integrate with this installed:
     - [x ] Tinker's Construct
     - [x ] Mine Factory Reloaded
     - [x ] Mine Addons
     - [x ] Moo Fluids
     - [x ] Waila
- [ x] I also have other mods installed
- [ x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ x] I am crashing and can provide my crash report(s)

## Additional Information
- [ ] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [ x] Java 8
- [ ] Minecraft Version:
     - [x ] 1.10.2

## Issue Description
Hey i am working on 2.3.1 version of FoolCraft and i am getting the crash below running 1.32 of mini moos

## Additional Information

[crash report](https://pastebin.com/2D3T90Ru)

**Comment by IRicTheCoder** [comment]
@scalda Even though it is being triggered by MiniMoos this is actually a problem with its Core. Just update the YetAnotherCore and it should be fixed :)

Btw, when are you releasing foolcraft 2.3.1?

**Comment by scalda** [comment]
hi thanks for this for some reason the twitch launcher didn't show there was an update i had to go and grab it manually
