### ISSUE TITLE
Mini Wheat not working

### ISSUE THREAD

**Issue by dxns-hub** [RicardoTheCoder/MiniMoos#12]
- [ x] I am using a release version of the mod
- [ ] I have mods that integrate with this installed:
     - [x ] Tinker's Construct
     - [x ] Mine Factory Reloaded
     - [ ] Mine Addons
     - [ ] Moo Fluids
     - [ ] Waila
- [x ] I also have other mods installed
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## Additional Information
- [ ] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [ x] Java 8
- [ ] Minecraft Version:
     - [x ] 1.10.2

## Issue Description
Mini wheat not working when trying to breed, used on a foolcraft server.

**Comment by IRicTheCoder** [comment]
@dxn000 Breeding moos isn't like normal minecraft animals, they have different rules of breeding. This is all explained in the mod's wiki https://github.com/RicardoTheCoder/MiniMoos/wiki/Breeding-Moos.

If you need further information or another explanation on this, please feel free to ask :)
