### ISSUE TITLE
Server Console spam

### ISSUE THREAD

**Issue by Dinip** [RicardoTheCoder/MiniMoos#13]
- [x] I am using a release version of the mod
- [ ] I have mods that integrate with this installed:
     - [x] Tinker's Construct
     - [x] Mine Factory Reloaded
     - [ ] Mine Addons
     - [x] Moo Fluids
     - [x] Waila
- [x] I also have other mods installed
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## Additional Information
- [ ] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [x] Java 8
- [ ] Minecraft Version:
     - [x] 1.10.2

## Issue Description

Boas, desculpa estar a escrever em PT mas já que és PT é mais facil do que estar a "falar" em ingles! :)
Tenho um server de foolcraft e desde que saiu o ultimo update em que se passou a usar o MiniMoos em vez do Fluid Cows, a consola do server anda com o spam (warn, sobre as minimoos). A cada minuto aparece umas linhas como essas: https://pastebin.com/Y18PFurP
Era so para saber se é algum "bug" por parte do mod ou se por parte do Foolcraft. Sim é so um warn e em principio nao é problema nenhum, mas ter os logs todos "spamados" é um bocado chato :)

**Comment by IRicTheCoder** [comment]
@Dinip12 Peço desculpa pela demora na resposta, e para esclarecer, na realidade não é nem um problema do mod nem um problema do foolcraft. Existem varios mods que fazem esse warn, mas o warn em si é problema do minecraft.

Aparentemente o Forge suprime os warns dos mobs vanilla onde isso acontece, no caso do MiniMoos, estou a tentar encontrar uma solução para o problema, ou uma maneira de evitar que esse warn apareça ou de contornar o problema que o leva a aparecer (sendo que é tudo causado pelo vanilla, é complicado fazer um fix para isso).

**FOR THOSE THAT MIGHT HAVE THE SAME ISSUE, HERE IS THE EXPLANATION IN ENGLISH:**
The OP asked what are the "Keeping entity" spams in the console, so here is the answer:

This is not a problem with the mod or a problem with foolcraft. There are many mods that make this spam in the console, but the warn is a problem of the vanilla minecraft.

Apparently forge suppressed those warning from the vanilla mobs, when it comes to MiniMoos, I'm looking for a solution, either to suppress the warnings or to counter the problem itself (has this is a vanilla problem it is taking me a while to find a fix).
