### ISSUE TITLE
Molten infinity moos do not spawn, cause crash when forced

### ISSUE THREAD

**Issue by benhavo** [RicardoTheCoder/MiniMoos#14]
- [ ] I am using a release version of the mod
- [ X] I have mods that integrate with this installed:
     - [ X] Tinker's Construct
     - [ X] Mine Factory Reloaded
     - [ X] Mine Addons
     - [ X] Moo Fluids
     - [ X] Waila
- [ X] I also have other mods installed
- [ X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ X] I am crashing and can provide my crash report(s)

## Additional Information
- [ ] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [X ] Java 8
- [ ] Minecraft Version:
     - [X ] 1.10.2

## Issue Description
Infinity Mini Moos do not spawn. When forced to spawn via setting all "fluid spawns" to 0 in the config file with molten infinity set to 100, the game crashes upon loading new chunks. Currently on the Foolcraft2 modpack version 2.3.1 with Optifine 10.2.1 HD U E3 (also occurs without Optifine).

## Additional Information
Crash report is too big for pastebin...please advise

**Comment by IRicTheCoder** [comment]
@benhavo send me the .txt file of the crashreport, and I will look into that, as this wasn't happen to me and I have found multiple infinity moos when playing foolcraft 2.3.1.

**Comment by benhavo** [comment]
Thanks for the quick reply. Awesome mod btw. 

[crash-2017-10-16_10.47.41-server.txt](https://github.com/RicardoTheCoder/MiniMoos/files/1387880/crash-2017-10-16_10.47.41-server.txt)

**Comment by benhavo** [comment]
I apologize. I did not intend to close the issue with that comment.

**Comment by IRicTheCoder** [comment]
@benhavo Are you playing in a server or only in a client? if you are playing in a server, might the configs be different? That might cause this issue, also it could be just the "stupid" ticking entity stuff that minecraft still does. There is a page on the FoolCraft's Wiki about how to fix it.

However I have an idea of what caused it to be triggered, I would say put the config back as it was and test if it gives any errors, if it doesn't that error will be fixed in the next version.

But it is not a problem with the spawning of Molten Infinity, as this cow spawns in the nether, because its temperature is above lava.

**Comment by benhavo** [comment]
@RicardoTheCoder Thanks for the info. I'm playing on a client, and the setup I followed has the pack set up on a local server (I guess I should try changing that for some performance boost). I've replaced the config, and it is working as normal again. This must be karma telling me to stop trying to cheat... Hopefully I'll find that infinity moo soon with the default config!

**Comment by IRicTheCoder** [comment]
@benhavo Check the nether, in the default config it spawns there, you should eventually find it, as it is more common then with Moo Fluids, this will be changed in a newer version of the mod as it will select the spawning places better.

If you have it solved for now, don't close this issue so I remember to fix the problem with it giving that error, thanks.
