### ISSUE TITLE
Startup crash with 1.3.2

### ISSUE THREAD

**Issue by brisingraerowing** [RicardoTheCoder/MiniMoos#16]
- [X] I am using a release version of the mod
- [X] I have mods that integrate with this installed:
     - [X] Tinker's Construct
     - [X] Mine Factory Reloaded
     - [ ] Mine Addons
     - [ ] Moo Fluids
     - [X] Waila
- [X] I also have other mods installed
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report(s)

## Additional Information
- [X] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [X] Java 8
- [X] Minecraft Version:
     - [X] 1.10.2

## Issue Description
Crash when starting the game.

## Reproduce Steps

Try to load the game.

## Additional Information
[Crash Log](https://gist.github.com/BrisingrAerowing/666d8238467fc94467bdda1634c03dfa)

**Comment by IRicTheCoder** [comment]
@BrisingrAerowing A new version is being uploaded to fix this, just update when its ready and it should fix it :)

EDIT: Its Approved already

EDIT2: Adding a new version as the previous got a problem

EDIT3: Now its approved :P
