### ISSUE TITLE
Q: 1.12.1+ support?

### ISSUE THREAD

**Issue by leasoncre** [RicardoTheCoder/MiniMoos#18]
Will this mod be available for use with 1.12.1+(or later versions) packs in the future? if so, when might we see it available?
Thanks.

**Comment by IRicTheCoder** [comment]
I do plan on getting the mod updated to versions above 1.10.2, but only after I have finished all the features I want to implement. However, I don't have an actual date for that nor can I give you an accurate time.

**Comment by leasoncre** [comment]
thanks! have fun coding!
