### ISSUE TITLE
Mini Moo Wont Breed

### ISSUE THREAD

**Issue by killerkitt** [RicardoTheCoder/MiniMoos#2]
- [x] I am using a release version of the mod
- [x] I have mods that integrate with this installed:
     - [x] Tinker's Construct
     - [x] Mine Factory Reloaded
     - [x] Mine Addons
     - [x] Moo Fluids
     - [x] Waila
- [x] I also have other mods installed
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## Additional Information
- [ ] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [ ] Java 8
- [ ] Minecraft Version:
     - [x] 1.10.2

## Issue Description
FoolCraft 2 most up to date version of it and i cannot breed any mini moo cows with the miniwheat

## Reproduce Steps
make mini wheat right click two cows of differnt or same fluid and it wont make them do anything

**Comment by IRicTheCoder** [comment]
@killerkitt This might be a problem in the information I provided on the mod wiki or curse page.

I state these two things:
- Mini Wheat to breed them, made with wheat and blaze powder (can only attract without Tinker's Contruct Addon)
- Allows cows to be breed to give alloy fluids (it only works with alloys that only require 2 fluids)

Let me clarify that for you, you can only breed cows that have fluids that can make an alloy result. An example will be breeding a water and lava cow to give an obsidian cow.

The mini wheat does get consumed even if they don't breed, this was intended as a way to balance the breeding process when alloy cows also spawn in the world. However, I can either add a configuration for that or remove that "feature".

I will alter the description on this to make it more clear.

Hope that this helps you out ;)
