### ISSUE TITLE
Exception in server tick loop - minimoos / fluidmoos

### ISSUE THREAD

**Issue by Lepercy** [RicardoTheCoder/MiniMoos#20]
- [ ] I am using a release version of the mod
- [x] I have mods that integrate with this installed:
     - [x] Tinker's Construct
     - [x] Mine Factory Reloaded
     - [x] Mine Addons
     - [x] Moo Fluids
     - [x] Waila
     - [x] Avaritia
- [x] I also have other mods installed
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)

## Additional Information
- [x] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [x] Java 8
- [x] Minecraft Version:
     - [x] 1.10.2

## Issue Description
On startup, when the world is generating a spawn, it shutsdown for Null Fluid supplied to fluidstack error.

## Reproduce Steps
Installed FoolCraft 2.4 version, Forge version 2511, Spongeforge as well 2281. Preconfigured Nucleus and some configs for some of the mods. Started up server. and It shut itself down.

## Additional Information
As above, https://pastebin.com/7Y1XUZV4

**Comment by IRicTheCoder** [comment]
@Lepercy 3 things a need to know, which configs did you change? Did you add any other mods besides SpongeForge? And did you use any plugins with your SpongeForge?

SpongeForge generates errors with some mods, this could be the case of my mod, and that is something that I cannot fix, as it is the changes SpongeForge does to the main forge code that creates those errors.

Try running the server either without sponge forge or without either added mods or without changing the config and see if it works. If it doesn't then might be another problem, which will be hard to find since I have the FoolCraft 2.4 running on my server without any issues.

Also are you updating from a version before MiniMoos was added? If so it might be a problem with Moo Fluid Cows and might not be that easy to fix.

PS: If sponge forge is only to fix the "move too quickly" error there is another mod for that, called MTQ, you can find it on curse, its a server only mod and should fix the "move too quickly" error

**Comment by Lepercy** [comment]
I have Nucleus for 1.10.2 added as well as for configuring i did reconfigure the minimoos a bit. I dont want my players having access to the molten infinity cow easily..... i want this server I am creating to be a HardMode server and I want them to struggle to get this infinity cow. I did change a few other things in the config. will post pastebin below.....   https://pastebin.com/dUVaRPZw

**Comment by IRicTheCoder** [comment]
@Lepercy I forgot to add this to the config but "I:"Molten Infinity"=0.5" is invalid it can only accept integer numbers, so no decimal values. That should be converted to 1 or 0 as it is done by forge itself.

Setting that to 1 will also make it extremely hard to find, also you can increase the rate of another fluids as that will make infinity even harder to get.

I don't see any more problem then that, I will really suggest you try it without sponge forge to see if it works.

**Comment by Lepercy** [comment]
Well, to update you, i reconfigured all the minimoos to where id like them, set infinity to 1 and tried it and got same "null stack error" So then, disabled Sponge, and it loaded. I dont know what I am going to do for the rest of the server if this is how I have to run it, straight forge. I have a lower diffuculty version of this already on just Forge and were having issues doing our Administrative things for server. We are running FE but it isnt that good. Might try Thut but just thought I would let you know this will cause more problem not being compatable with Sponge, than necessary...

**Comment by Lepercy** [comment]
welp loaded the server, got on started moving around and crash...

01.11 11:54:35 [Server] Server thread/WARN [FML]: ****************************************
01.11 11:54:35 [Server] Server thread/WARN [FML]: *  at java.util.Formatter.format(Unknown Source)...
01.11 11:54:35 [Server] Server thread/WARN [FML]: *  at java.util.Formatter$FormatSpecifier.print(Unknown Source)
01.11 11:54:35 [Server] Server thread/WARN [FML]: *  at java.util.Formatter$FormatSpecifier.printString(Unknown Source)
01.11 11:54:35 [Server] Server thread/WARN [FML]: *  at net.minecraft.entity.Entity.toString(Entity.java:2324)
01.11 11:54:35 [Server] Server thread/WARN [FML]: *  at com.ricardothecoder.minimoos.entities.EntityFluidMoo.func_70005_c_(EntityFluidMoo.java:621)
01.11 11:54:35 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:46)
01.11 11:54:35 [Server] Server thread/WARN [FML]: * Null fluid supplied to fluidstack. Did you try and create a stack for an unregistered fluid?
01.11 11:54:35 [Server] Server thread/WARN [FML]: ****************************************

**Comment by IRicTheCoder** [comment]
@Lepercy Did you remove or run the game with some fluid that is not present anymore? If you did then it is trying to load a moo that contains a non existent fluid. It might not even be sponge at all.

I forgot to mention this before, so I'm sorry for the trouble it might cause you.

EDIT: I'm going to see if it is possible to prevent this on the mod itself.

**Comment by IRicTheCoder** [comment]
@Lepercy This should be fixed in the new version of the mod, if any moo contains a missing fluid or a bugged fluid it will show as "INVALID FLUID -" followed by the fluids registry name. It should not crash anymore but still having invalid fluids could be a problem so you should also check that.
