### ISSUE TITLE
Only Forsaken Moos Spawning in the End

### ISSUE THREAD

**Issue by chimeralchimera** [RicardoTheCoder/MiniMoos#21]
- [x] I am using a release version of the mod
- [x] I have mods that integrate with this installed:
     - [x] Tinker's Construct
     - [x] Mine Factory Reloaded
     - [x] Mine Addons
     - [x] Moo Fluids
     - [x] Waila
     - [x] Avaritia
- [x] I also have other mods installed
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## Additional Information
- [x] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [x] Java 8
- [x] Minecraft Version:
     - [x] 1.10.2

## Issue Description
Forge 12.18.3.2488
Foolcraft 2 Modpack

In the End, the only moos I can find with the current version of Mini Moos (1.3.3) are Forsaken Moos, and even these seem to be rather rare. I spent a good 30 to 40 minutes exploring the end looking for mini moos, and in that time, found only Forsaken Moos. When I downgraded back to 1.2 (I'm not sure if other versions of 1.3 will have this problem or not), I found a cluster of normal moos within a minute or two.

It might be worth mentioning that I hadn't entered the End prior to using 1.3.3.

## Reproduce Steps
Start a new world, go to the End, slay the Dragon, and hunt for moos in 1.3.3.

## Additional Information
Love the mod, hope this wont be too hard to fix.

**Comment by IRicTheCoder** [comment]
@chimeralchimera Send me your config file for the minimoos, it might be a problem there.

**Comment by chimeralchimera** [comment]
Okay, here you go. 
[minimoos.zip](https://github.com/RicardoTheCoder/MiniMoos/files/1439553/minimoos.zip)

**Comment by IRicTheCoder** [comment]
@chimeralchimera Did you add any new mods to the pack? There isn't a problem in the config, and that is strange because in my server, they keep on spawning with no problem.

**Comment by chimeralchimera** [comment]
The only thing I've added is Optifine. I would have mentioned it earlier, but I forgot until you asked if I added anything (^_^;). It seems strange that it wouldn't cause any problems with 1.2 but would with 1.3.3 though.

The only other things I can think to mention are that I'm playing on a singleplayer world and that I'm running it through MultiMC because Twitch kept having a bunch of problems, and I could never get it to run through it.

**Comment by IRicTheCoder** [comment]
@chimeralchimera I will check that and then I will get back to you. Optifine and MultiMC shouldn't be a problem.

**Comment by IRicTheCoder** [comment]
@chimeralchimera I just uploaded a new version 1.4.1 that should fix those issues. Should be available shortly.

**Comment by chimeralchimera** [comment]
Awesome, thanks!
