### ISSUE TITLE
Compatibility With Extreme Reactors

### ISSUE THREAD

**Issue by BeastlyNinja11** [RicardoTheCoder/MiniMoos#22]
There is compatibility with Iskallium Reactors, so do you think you can make it possible to add compatibility (for the Tinkers' Construct casting) for the Yellorium/Yellorite? I couldn't find anything after a few hours of searching. Thanks in advance!

**Comment by IRicTheCoder** [comment]
@BeastlyNinja11 The Iskallium Reactors and Avaritia Compatibility were only added for the purpose of explaining how to create liquids that can only be obtained by feeding moos with certain items. I'm planning on making those fluids part of another mod I'm making, removing the purpose of having the fluids directly in the moos mods as that is not suppose to happen.

As of this moment I do not plan on adding new addons like those into mini moos, but I will take your suggestion into consideration, and if not in mini moos maybe I could add that into my other mod.

**Comment by brisingraerowing** [comment]
You can use CraftTweaker / ModTweaker to allow casting liquid yellorium into blocks and ingots, and allow melting down yellorium things into liquid form. Liquid yellorium is actually added by Extreme Reactors itself (it's what appears in the fuel rods AFAIK).

Here's a simple script to add this:
```text
// Melting
// Yellorium
mods.tconstruct.Smeltery.addMelting(<liquid:yellorium> * 100, <bigreactors:ingotmetals>, 700);
mods.tconstruct.Smeltery.addMelting(<liquid:yellorium> * 900, <bigreactors:blockmetals>, 700);
mods.tconstruct.Smeltery.addMelting(<liquid:yellorium> * 200, <bigreactors:brore>, 700);
mods.tconstruct.Smeltery.addMelting(<liquid:yellorium> * 100, <bigreactors:dustmetals>, 700);
// Casting
mods.tconstruct.Casting.addBasinRecipe(<bigreactors:blockmetals>, <liquid:yellorium> * 900, null);
mods.tconstruct.Casting.addTableRecipe(<bigreactors:ingotmetals>, <liquid:yellorium> * 100, <tconstruct:cast_custom>);
```

This script will work in 1.10.2. ModTweaker for 1.12.2 changed some arguments around and modified some object names.
