### ISSUE TITLE
Compatibility with RFTools Dimensions

### ISSUE THREAD

**Issue by lDisciple** [RicardoTheCoder/MiniMoos#24]
- [ ] I am using a release version of the mod
- [x] I have mods that integrate with this installed:
     - [ x] Tinker's Construct
     - [ x] Mine Factory Reloaded
     - [ ] Mine Addons
     - [ x] Moo Fluids
     - [ x] Waila
     - [ ] Avaritia
- [ x] I also have other mods installed
- [ x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ x] I am crashing and can provide my crash report(s)

## Additional Information
- [ ] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [ x] Java 8
- [ ] Minecraft Version:
     - [ x] 1.10.2

## Issue Description

Game crashes when going into an RFTools dimension as the mod appears to try to retrieve the values for what moos are able to spawn in the custom dimension. Then a NPE is thrown as there is no failsafe for custom dimensions, only the nether, overworld and end.

## Reproduce Steps
Create a RFTools dimension move around a bit till a few chunks load then eventually a NPE will be thrown causing the game to crash.

## Additional Information
https://pastebin.com/PMLqSQW6

**Comment by IRicTheCoder** [comment]
@lDisciple Update to the new version of the mod, this should be fixed on version 1.4.1 as stated in this issue #23 which is about the exact same thing.

If the problem persists let me know
