### ISSUE TITLE
Breaks with MineAddons 1.3

### ISSUE THREAD

**Issue by brisingraerowing** [RicardoTheCoder/MiniMoos#25]
- [x] I am using a release version of the mod
- [x] I have mods that integrate with this installed:
     - [x] Tinker's Construct
     - [x] Mine Factory Reloaded
     - [x] Mine Addons
     - [ ] Moo Fluids
     - [x] Waila
     - [x] Avaritia
- [x] I also have other mods installed
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)

## Additional Information
- [x] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [x] Java 8
- [x] Minecraft Version:
     - [x] 1.10.2

## Issue Description
MineAddons recently released v1.3, which changes the mod namespace layout, causing a crash.

## Reproduce Steps
Use MiniMoos with MineAddons 1.3

## Additional Information
[Crash Log](https://gist.github.com/BrisingrAerowing/7e06e037f9c866c3a5e7b99e0947ea8c)

**Comment by IRicTheCoder** [comment]
@BrisingrAerowing Thanks for pointing this out, I'm going to fix it as soon as possible.

**Comment by IRicTheCoder** [comment]
@BrisingrAerowing Should be fixed in the new version (1.4.2)
