### ISSUE TITLE
Mushroom cows not spawn (only Mini Moo)

### ISSUE THREAD

**Issue by Lexon78** [RicardoTheCoder/MiniMoos#26]
- [x] I am using a release version of the mod
- [x] I have mods that integrate with this installed:
     - [x] Tinker's Construct
     - [x] Mine Factory Reloaded
     - [x] Mine Addons
     - [ ] Moo Fluids
     - [x] Waila
     - [x] Avaritia
- [x] I also have other mods installed
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## Additional Information
- [ ] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [x] Java 8
- [ ] Minecraft Version:
     - [x] 1.10.2

## Issue Description
Modpack FoolCraft
For quest i must kill 64 Mushroom Cows, but this cow is spawn only if world is generated. I found two Mushroom Islands and on both was only MiniMoo and no one Mushroom Cow.
Can be this cow spawned?

**Comment by IRicTheCoder** [comment]
@Lexon78 Mini Moos should not be causing problems with those spawns, essencially because it does not change the spawns for mushroom cows. There might be something else causing some interference with the spawns of those cows.

Do you have more mods installed besides those that come with FoolCraft?

**Comment by Lexon78** [comment]
I add only this mods to FoolCraft:
ArchitectureCraft-1.7.3-mc1.10.2.jar
ChickenChunks-1.10.2-2.2.0.52-universal.jar
OptiFine_1.10.2_HD_U_E3.jar

My MushroomIslands look like this (my 1st found):
https://youtu.be/dKEC13VHPN0?t=44m

**Comment by IRicTheCoder** [comment]
@Lexon78 Those mods should not cause any issues, or at least not any I know. Mushroom Cows are harder to find then most mobs, but should not stop spawning because of MiniMoos. I have found mushroom cows on my server with MiniMoos installed without any problems, might be they take longer to spawn because there are other cows spawning there too.

I will however look into this to see if it is in fact a MiniMoos problem or not. If it is I will release a fix as soon as I can.

**Comment by Lexon78** [comment]
Now i try again on creative map in FoolCraft and i found 3 Mushroom isles only with MiniMoo and 1 Mushroom isle with MiniMoo and Mushroom cow. Then this cow can be generated with mod MiniMoo but its extremly rare.

**Comment by IRicTheCoder** [comment]
@Lexon78 Just deployed a new version of the mod, moos should no longer spawn on mushroom islands.
