### ISSUE TITLE
Iskallium/neutronium forced change not working?

### ISSUE THREAD

**Issue by Vertigo81** [RicardoTheCoder/MiniMoos#28]
- [x] I am using a release version of the mod
- [x] I have mods that integrate with this installed:
     - [x] Tinker's Construct
     - [x] Mine Factory Reloaded
     - [x] Mine Addons
     - [x] Moo Fluids
     - [x] Waila
     - [x] Avaritia
- [x] I also have other mods installed
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## Additional Information
- [ ] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [ ] Java 8
- [x] Minecraft Version:
     - [x] 1.10.2

## Issue Description

I was excited when I saw the patch notes, but these don’t see to work.
I’m playing the most recent foolcraft patch, and I’ve double checked the Config files and made sure avaritia and iskallium integrations are enabled.

Fluid moos will consume the feed (iskallium/neutron piles), and their milking cooldown resets, but they don’t change types.  When I wait for the timer and milk them I get their normal fluids.  I fed one a few stacks of neutrons to see if there was some quantity required, but nothing changed.

**Comment by Vertigo81** [comment]
Update- actually it seems iskallium will work but only on a nether spawned cow?  It failed on the first bunch I tried but eventually worked on a copper cow

**Comment by IRicTheCoder** [comment]
@Vertigo81 I'm sorry for the delayed response, but those are working fine, the change for a neutronium moo is 1/2000 meaning that you have to atleast feed 2000 piles of neutrons to actually get any chance. Last one I made in my server took me around 3000+ piles of neutrons. It is suppose to be an end game fluid/moo.

Iskallium works in all moos, as those the liquified neutronium. However there are chances, if I remember currenctly iskallium is 1/20. Not sure though, and can't really check that now.

Hope this info helps

**Comment by Vertigo81** [comment]
Ah, well that’s good.  You may want to put something about it being a chance somewhere in the patch notes though.  There’s no mention.

**Comment by IRicTheCoder** [comment]
@Vertigo81 Currently I can't edit that but I will get to it as soon as possible. I'm away in a Game Dev Event and won't be back for a few days.
