### ISSUE TITLE
Nullpointer exception

### ISSUE THREAD

**Issue by AlmightyZing** [RicardoTheCoder/MiniMoos#3]
- [ X ] I am using a release version of the mod
- [ X ] I also have other mods installed
- [ X ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ X ] I am crashing and can provide my crash report(s)

## Additional Information
- [ ] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [ ] Java 8
- [ ] Minecraft Version:
     - [ X ] 1.10.2

## Issue Description

Forge 1.10.2-12.18.3.2422

Updated world from Foolcraft 2.1 to 2.2, which added this mod.
Everything was fine for about 20 minutes, then two players who were near mini moo cows got kicked from the server and couldn't rejoin. A third who wasn't near them remained on the server.

I did a server restart to see if that would fix the issue, but I still could not log on. Moments later the server itself crashed (see the crash report below).

## Reproduce Steps
Unsure of the exact cause, but I had a few dozen mini moo cows (no more than 9 in a 5x5 area), and had used both the auto spawner (MFR) and the powered spawner (Ender IO) and both had been powered off at the time of the crash. (Side note, is it intended that the auto spawner does not produce exact copies?)

## Additional Information
Server crash
[crash-2017-10-03_23.02.02-server.txt](https://github.com/RicardoTheCoder/MiniMoos/files/1354165/crash-2017-10-03_23.02.02-server.txt)

Console output of client crash:
https://pastebin.com/qfaz2WWy

**Comment by scalda** [comment]
same crash as here #https://github.com/scalda/FoolCraft/issues/783

**Comment by IRicTheCoder** [comment]
@AlmightyZing @scalda I tested this with Ender IO Spawners and had no problems also tried it with MFR and it yields no problems or crashes, but I know what is causing that issues and it should not have corrupted your save, as long as you update to a fixed version.

I will look into this, and about the exact copies it was creating unexpected results, so to prevent crashes I made a workaround that may not allow exact copies to be spawned.

My mod implements things differently from Moo Fluids, so it can always have cows with fluids without yielding empty buckets and stuff.

**I will try to make a fixed version as soon as possible, and you can simply update your version to that**

**Comment by AlmightyZing** [comment]
Thanks, It did somehow corrupt the save, but after loading in my backup I haven't had any issues since.

**Comment by IRicTheCoder** [comment]
@AlmightyZing it was because the error creates a loop of nullpointers, after the fix it should fix itself and prevent further problems. I'm addressing it now and hope to have a fixed version soon ;)

**Comment by IRicTheCoder** [comment]
@AlmightyZing just added a new version of the mod to curse, should be ready to update soon. It is version 1.1.1 and I would ask that you update it manually on your pack and test it. It should work fine now.

Exact copies will remain disabled, so I can better ensure that cows do not spawn with bugged fluids (that system is what prevents the exact copy ones)

EDIT: This should also fix the corrupted worlds, so you can access them again.

**Comment by IRicTheCoder** [comment]
Should be solved as of c575034431344a4ef8af884db2c1d7f72f5f7a78
