### ISSUE TITLE
1.12.2 crash with MooFluids

### ISSUE THREAD

**Issue by brisingraerowing** [RicardoTheCoder/MiniMoos#31]
- [x] I am using a release version of the mod
- [x] I have mods that integrate with this installed:
     - [x] Tinker's Construct
     - [ ] Mine Factory Reloaded
     - [ ] Mine Addons
     - [x] Moo Fluids
     - [ ] Waila
     - [ ] Avaritia
     - [ ] Twilight Forest
     - [ ] Aether Legacy
- [x] I also have other mods installed
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)

## Additional Information
- [x] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [x] Java 8
- [x] Minecraft Version:
     - [ ] 1.10.2
     - [x] 1.12.2

## Issue Description
Crash when installed with MooFluids.

## Reproduce Steps
Run with MooFluids.

## Additional Information

[Crash Log](https://gist.github.com/BrisingrAerowing/2611e01722da9457fd213493f6f376b5)

**Comment by IRicTheCoder** [comment]
@BrisingrAerowing Thats an easy fix, it will be fixed in the next version, with some other fixes and changes.

Thanks for pointing this out :)

**Comment by IRicTheCoder** [comment]
@BrisingrAerowing Sorry for the time it took to fix this. Should work now with the new beta version, also update the Yet Another Core so it will ensure you don't it other similar problems.
