### ISSUE TITLE
Cant find the Demon moo or Sacred moo in the overworld, and cant spawn them using MFR

### ISSUE THREAD

**Issue by 3jlowes** [RicardoTheCoder/MiniMoos#5]
- [x] I am using a release version of the mod
- [x] I have mods that integrate with this installed:
     - [x] Tinker's Construct
     - [x] Mine Factory Reloaded
     - [x] Mine Addons
     - [x] Moo Fluids
     - [x] Waila
- [x] I also have other mods installed
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## Additional Information
- [x] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [x] Java 8
- [x] Minecraft Version:
     - [x] 1.10.2

## Issue Description
Foolcraft Version 2.3, Cant find demon or sacred moo and cant spawn them using mfr.

**Comment by iamshift** [comment]
> Demon Moo spawn in the nether and Sacred Moo in the overworld.  

from [wiki](https://github.com/RicardoTheCoder/MiniMoos/wiki)

**Comment by IRicTheCoder** [comment]
@3jlowes Let me just quote myself from the mod description/wiki

> - Fluid Temperatures below water (300) only spawn in the end
> - Fluid Temperatures above or equal to lava (1300) only spawn in the nether
> - Fluid Temperatures between those two spawn in the overworld.
> - Demon Moo spawns in the nether and Sacred Moo in the overworld.

Also, Demon Moo and Sacred Moos are different entities from the fluid moos. And they are extremely rare to find. 

EDIT: If there is a crash-report of something please do send me that
