### ISSUE TITLE
Startup Crash with 1.2

### ISSUE THREAD

**Issue by brisingraerowing** [RicardoTheCoder/MiniMoos#6]
- [x] I am using a release version of the mod
- [x] I have mods that integrate with this installed:
     - [x] Tinker's Construct
     - [x] Mine Factory Reloaded
     - [ ] Mine Addons
     - [ ] Moo Fluids
     - [x] Waila
- [x] I also have other mods installed
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)

## Additional Information
- [x] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [x] Java 8
- [x] Minecraft Version:
     - [x] 1.10.2

## Issue Description
Crash on startup (Invalid Argument)
Forge 2488

## Reproduce Steps
Try to start with 1.2

## Additional Information

[Crash Log](https://gist.github.com/BrisingrAerowing/3f17de27a7895ec0bac3ea8b6489dc9d)

I have a LOT of mods, and this may be one of them having an invalid fluid.

**Comment by IRicTheCoder** [comment]
@BrisingrAerowing I found the problem, it seems to be with forestry fluids, they are registered and implemented in a custom way, using almost nothing from the forge universal system.

This prevents me from getting all those fluids and actually have them on cows or in a list of containable fluids.

So to allow the use of mods with custom implementations and without causing errors, I updated the YetAnotherCore (RicardoTheCoder/YetAnotherCore@919ffe56ae1f04a003ac6d52f5097dfed769c19d) which is the core for MiniMoos (and where the fluids are obtained from) with a fix that should allow forestry and other mods with the same issue to load without any problems.

The new version should be arriving shortly on curse/twitch launcher ;)

EDIT: It is approved already and should be available for download
