### ISSUE TITLE
Spawning Exact copy via MFR Auto Spawner

### ISSUE THREAD

**Issue by Necro9227** [RicardoTheCoder/MiniMoos#9]
- [ ] I am using a release version of the mod
- [x] I have mods that integrate with this installed:
     - [x] Tinker's Construct
     - [x] Mine Factory Reloaded
     - [x] Mine Addons
     - [x] Moo Fluids
     - [x] Waila
- [x] I also have other mods installed
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## Additional Information
- [ ] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [x] Java 8
- [ ] Minecraft Version:
     - [x] 1.10.2

## Issue Description

Using the Mine Factory Reloaded Auto Spawner to spawn an exact copy of the captured mini moo results in random moo instead

## Reproduce Steps
capture any mini moo in a safari net and set the MFR auto spawner to exact copy yes

## Additional Information
Using the Latest version of the Foolcraft2 modpack

**Comment by IRicTheCoder** [comment]
@Necro9227 This as been answered in issue #7 and it is both in the mod's description and the mod's wiki.

Quoting from the Mod's Description (on Curse):
> Exact Copies for the fluid moos are currently disabled to prevent bugged moos

This is currently in my to-do list, but it is not my priority at the moment. For now exact copies will either yield a random result or no result at all.
